version: '3.4'

services:
  ambev.developerevaluation.api:
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationapi
    container_name: ambev_developer_evaluation_api
    build:
      context: .
      dockerfile: Ambev.DeveloperEvaluation.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  ambev.developerevaluation.database:
    container_name: ambev.developerevaluation.database
    image: postgres:13
    environment:
      - POSTGRES_DB=developer_evaluation
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=ev@luAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped